# Generated by Django 4.2.7 on 2023-12-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'Rang'), ('size', "O'lcham")], max_length=255),
        ),
    ]
