# Generated by Django 4.2.3 on 2023-11-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_number',
            new_name='order_number',
        ),
    ]
