# Generated by Django 4.2.3 on 2023-11-07 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_oreder_number_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oreder_total',
            new_name='order_total',
        ),
    ]
