# Generated by Django 4.2.7 on 2023-12-20 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_orderproduct_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paymnet',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
