# Generated by Django 4.2.7 on 2023-12-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderproduct_variation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yangi'), ('Accepted', 'Qabul qilindi'), ('Completed', 'Yakunlandi'), ('Cancelled', 'Inkor qilindi')], default='New', max_length=10),
        ),
    ]
