# Generated by Django 4.2.7 on 2023-12-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cretaed_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='cretaed_at',
            new_name='created_at',
        ),
    ]
